### ISSUE TITLE
How to find new telegram-bot ?

### ISSUE THREAD

**Issue by realsamanrad** [rizaumami/tdbot.lua#12]
Hello,
I use telegram-bot nightly (180801) version downloaded from [valtman.name/telegram-bot](https://valtman.name/telegram-bot) .
How to find or compile the latest update of tdbot which supports new syntax of tdbot.lua wrapper that located on [github.com/rizaumami/tdbot.lua](https://github.com/rizaumami/tdbot.lua) .
For example, the {  _ = "user"} response, changed to: {  ["@type"] = "user"} and my current tdbot doesn't recognize it.
Cheers

**Comment by rizaumami** [comment]
- https://github.com/vysheng/tdbot
- https://github.com/rizaumami/tdbot
