### ISSUE TITLE
parse_mode Bug

### ISSUE THREAD

**Issue by SayedSadat** [rizaumami/tdbot.lua#16]
if text have more then 1 parse mode in a text  like
```<b>test</b> <b>test</b>```

bot crash and log is :

[ 1][t 0][1549041921.485059500][clilua.cpp:148][!Td]	FAILED TO PARSE LUA: [Error : 0 : Expected Array, got Object]

[ 0][t 0][1549041921.485291243][clilua.cpp:213][!Td]	lua: ./tdbot.lua:114: assertion failed!

[pid 81692] [time 1549041921] Signal: 6

**Comment by SayedSadat** [comment]
fixed with this commit!

https://github.com/giuseppeM99/tdbot/blob/e8a0c4bf5cc92bc8cc901c0042f7914304cc1163/clilua.cpp

**Comment by rizaumami** [comment]
`tdbot.lua` is just a lua warpper script, you better raise the issue directly to [upstream tdbot](https://github.com/vysheng/tdbot) instead.
