### ISSUE TITLE
Bot_Method_Invalid error shows when using getChatMessageByQuery with my bot

### ISSUE THREAD

**Issue by zyadomer999** [rizaumami/tdbot.lua#18]
Hello
Could you please tell me why this error occurs whenever I use getChatMessageByQuery with my bot?

Thanks

**Comment by rizaumami** [comment]
Perhaps because this repo's last update was two years ago, which is not compatible with newer methods.
And as far as I can see, there is no `getChatMessageByQuery` in [td_api.tl](https://raw.githubusercontent.com/tdlib/td/master/td/generate/scheme/td_api.tl).
