### ISSUE TITLE
join channel

### ISSUE THREAD

**Issue by gitacc92** [rizaumami/tdbot.lua#4]
hi, how to join channel with id (without link)?

function (importChatInviteLink) not work with channel username.

and how to start one bot with tdbot?

**Comment by rizaumami** [comment]
Use `setChatMemberStatus`:

```lua
setChatMemberStatus(chat_id, user_id, 'Member')
```

**Comment by afraz92** [comment]
(table)
  [@type] = (string) error
  [code] = (number) 3
  [message] = (string) Chat not found
---------------------------
thx but not work

**Comment by afraz92** [comment]
(table)
  [@type] = (string) error
  [code] = (number) 3
  [message] = (string) Chat not found

thx but not work...
