### ISSUE TITLE
parse_mode Bug

### ISSUE THREAD

**Issue by MyGitHub5** [rizaumami/tdbot.lua#5]
if i send msg with parse_mode and callback the callback funcation not work
see: https://github.com/rizaumami/tdbot.lua/blob/master/tdbot.lua#L106 and 720 and 1088

```
assert (tdbot_function (a.tdbody, a.callback or dl_cb, a.data))
    end, {tdbody = tdbody, callback = callback, data = data})
```
This fix the Bug...

and if you can add split msg by 4096 byte per msg for a long text msg
Thanks You, Amazing Work! :+1:

**Comment by rizaumami** [comment]
[A hope now it's fixed](https://github.com/rizaumami/tdbot.lua/commit/748f9d81c4b1041c8dcdf1eeee79bb16df257a45).

I've added a simple text splitter to `sendText` function, with one condition; no text formatting.
Splitting HTML or Markdown formatted text without breaking its formatting is complicated.

Thanx.

**Comment by MyGitHub5** [comment]
Thanks!

you can remove this line: https://github.com/rizaumami/tdbot.lua/blob/master/tdbot.lua#L117

and you forget to add my fix...

https://github.com/rizaumami/tdbot.lua/blob/master/tdbot.lua#L107 and 741 and 1109

edit to this: `assert (tdbot_function (a.tdbody, a.callback or dl_cb, a.data))`

**Comment by rizaumami** [comment]
My bad. [Hope it's fixed by now](https://github.com/rizaumami/tdbot.lua/commit/09ac8b21434fe5f82946d32a8cd1721d428343b2).
