### ISSUE TITLE
cant use more then 1 text in markDown

### ISSUE THREAD

**Issue by ShafiqSadat** [rizaumami/tdbot.lua#7]
when i use more then 1 text in markDown 
bot dont send text and crash

here is my code

```	
   if messageText == "test" then
	tdbot.sendText(msg.chat_id,msg.id,'`Test` `Test2`','md')
	end

**Comment by rizaumami** [comment]
Works in my machine™.

**Comment by ShafiqSadat** [comment]
Not works for me :(

**Comment by rizaumami** [comment]
Try to recompile lates `td` and pull the latest `tdbot.lua`.

**Comment by rizaumami** [comment]
I can now confirm this using [Vitaly's tdbot](https://github.com/vysheng/tdbot).
But, it's working fine using this fork: https://github.com/giuseppeM99/tdbot.

So, yes, it's not `tdbot.lua` bug.
